[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[profile.release]
# lto = "fat"
# panic = "abort"
# codegenunit = 1

[dev-dependencies]
criterion = "0.8.0"

[[bench]]
name = "solutions"
harness = false

[dependencies]
rayon = "1.11.0"
